spring.application.name=starwarschallenge
swapi.baseurl=https://www.swapi.tech/api
server.servlet.context-path=/star-wars-service/v1
spring.web.locale=en
spring.web.locale-resolver=fixed

# Configuración JWT
jwt.secret=miClaveSecretaSuperSeguraParaJWT2025StarWarsChallenge

# Usuarios para autenticación
app.users.admin.username=admin
app.users.admin.password=admin123
app.users.user.username=user
app.users.user.password=user123
